server:
  port: ":8080"
  rate_limit: 60
  rate_interval: 60

database:
  host: "127.0.0.1"
  port: "3307"
  user: "root"
  password: "root"
  dbname: "acheisuacara"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0 